### ISSUE TITLE
Add support for the Material Design in XAML Toolkit

### ISSUE THREAD

**Issue by sindilevich** [WildGums/Orc.Wizard#12]
It would be nice the wizard's supported styling in the manner of Google's Material Design. There is already an open-source project for Material Design styling for WPF, called Material Design in XAML Toolkit (https://github.com/ButchersBoy/MaterialDesignInXamlToolkit). There is a need incorporate the two into one solution and make Orc.Wizard pick up styling from the Toolkit.

**Comment by mkhomutov** [comment]
not sure if this feature will be ever applied to Orc.Wizard. Probably it could be applied to [Orchestra](https://github.com/WildGums/Orchestra). If you really need this feature, try to make pull request

**Comment by sindilevich** [comment]
@mkhomutov, thank you for your reply. I am not sure how Orc.Wizard and Orchestra correlate. But when you look at Orc.Wizard it consists from two conceptual parts: the wizard chrome (the breadcrumbs, and the buttons), and the user region, where the `catel:UserControl` derivatives live. While the user region's controls can be *probably* styled with the Material Design in XAML Toolkit to one's liking, the wizard's chrome is inaccessible.
Thus, what I suggest is adding the Material Design in XAML Toolkit support, so it'll influence every part of the wizard.

**Comment by mkhomutov** [comment]
the thing is all Orc.* components can be used independently, but main purpose of these components it to be used under Orchestra. That is why I told about Orchestra.
So, If we will apply styling stuff into all components separately, then we could get mess. All styles should be driven by the applications and not by the components.
Breadcrumbs harcoded in xaml (just a horizontal ListBox). So I don't think it would be easy to apply Material Design
I never used Material Design, but I think it requires a lot of work to support it in all components. Just don't have enough time to do this.

you can try to do that for Orc.Wizard if you want to. This is an open source project.

**Comment by GeertvanHorrik** [comment]
If you really need to override the chrome, then you will need to implement a custom WizardService. There you can use your own logic to show the (or a) wizard with custom chrome but still benefit a lot from the other logic (which is chrome-independent).

**Comment by herzbube** [comment]
Slightly off-topic: A tiny bit of styling can be had by defining two `SolidColorBrush` objects in the app .xaml:

* AccentColorBrush (applies to the selected breadcrumb item)
* AccentColorBrush4 (applies to the non-selected breadcrumb items)

For our application, which is a plain-looking business application, this was entirely sufficient, because it made the wizard blend in with the general company color scheme.

**Comment by sindilevich** [comment]
@herzbube, thank you for the hint. I do redefine those brushes to make the active and inactive breadcrumb items match colors with a color palette I had in mind. But the buttons and texts, and controls you may have in the wizard aren't stylized.

**Comment by GeertvanHorrik** [comment]
@sindilevich All Orc.* components will respect the accent color brushes. So if you use date pickers from Orc.Controls, they will be styled correctly.

If you want custom stuff to be styled, you will probably need to create custom styles for the controls that don't support this out of the box.

In our apps, even the buttons /textboxes are all styled correctly (but that is ultimately done by Orchestra). You could look into that one to see how we achieved that.

**Comment by sindilevich** [comment]
@GeertvanHorrik, I didn't know I could you special Orc.Controls. I'd probably give it a try. But what about the buttons: `Back`, `Cancel`, `Next`, `Finish`? I couldn't achieve any effect with the two aforedmentioned brushes on them...

**Comment by GeertvanHorrik** [comment]
See 
![image](https://cloud.githubusercontent.com/assets/1246444/17101459/fbc5c9de-5274-11e6-8d37-e6707039f6d0.png)

Style is defined in Orchestra:

https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Core/Orchestra.Core/Orchestra.Core.Shared/Themes/Controls.xaml#L10

**Comment by sindilevich** [comment]
@GeertvanHorrik, by me it is like attached below. Doesn't apply the yellow shades as in the breadcrumbs to the chrome buttons. Windows 10.

![image](https://cloud.githubusercontent.com/assets/475916/17104654/78a9ae4a-528c-11e6-855c-f0be894b4c94.png)

**Comment by GeertvanHorrik** [comment]
That's because you haven't specified the styles yet. You can either use Orchestra.Core and use the themehelper or add your own custom theme.
