### ISSUE TITLE
No taskbar icon for an Orc.Wizard application

### ISSUE THREAD

**Issue by sindilevich** [WildGums/Orc.Wizard#13]
When running the wizard, there is no taskbar icon for the application. The only way to bring the wizard window to background, once you switched to another window, is with `Alt+Tab`. How can I add a taskbar icon too?

Below is the code in `App.xaml.cs` that instantiates and displays the wizard
```C#
public partial class App : Application
{
	protected override void OnStartup(StartupEventArgs e)
	{
		ILanguageService languageService = ServiceLocator.Default.ResolveType<ILanguageService>();
		IWizardService wizardService = ServiceLocator.Default.ResolveType<IWizardService>();

		languageService.PreferredCulture = languageService.FallbackCulture = new CultureInfo("en-US");

		base.OnStartup(e);

		StyleHelper.CreateStyleForwardersForDefaultStyles();
		wizardService.ShowWizardAsync<InstallerWizard>();
	}
}
```

**Comment by GeertvanHorrik** [comment]
Currently this is indeed not supported. One way to solve this is to copy/paste the WizardWindow and set the ShowInTaskBar to true. This also requires a custom registration of the view inside the IViewLocator.

The wizard window does show up as modal though, so can you explain your behavior a bit? Are you showing multiple window at the same time? Or does activating the main window not bring the wizard to the front?

**Comment by sindilevich** [comment]
@GeertvanHorrik, thank you for your reply!

Actually, I do not have other windows besides the wizard itself. I am trying to build an installer, so when you double-click the `.exe` a wizard would show up.

As you can see in the code snippet above, I show the wizard straight at application start. This is not like you have in your demo project, when there is a window and a button that shows a wizard once clicked.

Hope my workflow makes sense.

**Comment by GeertvanHorrik** [comment]
Eventually this will lead up to other issues. WPF by default adds the first window as main window. As soon as you close it, it will close the app. If that is intentional, then we'll expose some Boolean value determining whether it should show up in the taskbar.

**Comment by sindilevich** [comment]
@GeertvanHorrik, yes, I think closing the installer wizard window in my case should shut down the entire application in any case. So in my scenario showing the wizard straight at the start is intentional.

**Comment by GeertvanHorrik** [comment]
Fixed.

**Comment by sindilevich** [comment]
It works. Thank you!
