### ISSUE TITLE
Where to place the Finish Wizard action/procedure?

### ISSUE THREAD

**Issue by roynickbutcher** [WildGums/Orc.Wizard#16]
Hello,

Sorry if this is the wrong place to put this question.  But, where do you tie in the procedure you want to run when the wizard is finished?

**Comment by mkhomutov** [comment]
You're using your implementation of `WizardBase` or `IWizard` (which is a wizard model) as an argument for `ShowWizardAsync()` method.
This method returns `bool` value. If it returned `true` then user has pushed 'Finish' button. Now you can use wizard model for implementing "Finish Wizard action"
Another way is you just can override `SaveAsync()` method in your implementation of `WizardBase` and/or in your implementations of `WizardPageBase`

**Comment by roynickbutcher** [comment]
Thanks for the info.  One more question.  What is the best way to access the ViewModels of the individual pages? wizard.Pages?

**Comment by mkhomutov** [comment]
why you need to get access to the ViewModel of page? you can use another way. You can (should) pass your data like this: PageView <=> PageViewModel <=> PageModel (WizardPageBase)
in such case your can always get access to required data from wizard
