### ISSUE TITLE
Show wizard with an existing object

### ISSUE THREAD

**Issue by bpcuong2013** [WildGums/Orc.Wizard#17]
Hi, I have a question on how to display a wizard with an existing model object. 
It's really great if the Orc.Wizard.Example.NET40 example project includes saving as well as loading an existed model. Thanks!

**Comment by GeertvanHorrik** [comment]
You should set up a Wizard model. This can be anything, and can include any info you want it to contain. Whenever the wizard is saved, the wizard model will have the updated info.

**Comment by cuong-hovit** [comment]
Thanks for your response. I have another question. How do we show a modal window from the wizard? Thanks!
