### ISSUE TITLE
Prevent wizard from closing if something wrong from server

### ISSUE THREAD

**Issue by bpcuong2013** [WildGums/Orc.Wizard#18]
Click on Finish button of Wizard, we call server to save data. If server returns user error, how do we prevent Wizard from closing, and move back to a specified page to let user edit? Thanks!

**Comment by GeertvanHorrik** [comment]
You should create a separate page where you submit the data. If it fails, you can navigate back to the selected page.

**Comment by cuong-hovit** [comment]
I add a custom class that extends from WizardBase and overwrite SaveAsync method that would be called when user clicks on Finish button. From this SaveAsync method, I try to navigate to the selected page if server returns failed but no luck.
Would you like to provide some example lines of code. Thanks!

**Comment by cuong-hovit** [comment]
Do you mean to define a custom class that extends from SummaryWizardPage ? Thanks!

**Comment by bpcuong2013** [comment]
I add a custom class that extends from WizardBase and overwrite SaveAsync method that would be called when user clicks on Finish button. From this SaveAsync method, I try to navigate to the selected page if server returns failed but no luck.
Would you like to provide some example lines of code. Thanks!

**Comment by bpcuong2013** [comment]
Do you mean to define a custom class that extends from SummaryWizardPage ? Thanks!

**Comment by GeertvanHorrik** [comment]
Yes, I would indeed create a separate page at the end (after the SummaryWizardPage).
