### ISSUE TITLE
Allow to customize the target for Next / Previous

### ISSUE THREAD

**Issue by herzbube** [WildGums/Orc.Wizard#3]
Currently Orc.Wizard is designed so that the user must step through all wizard pages in a sequential manner. There are use cases, however, that require a more flexible approach, e.g. skip one or more wizard pages based on the user's answers from a previous page. Unless I have overlooked something, this is currently not possible in Orc.Wizard.

This is a feature request to extend Orc.Wizard so that it allows the client code to customize the target for the Next / Previous buttons.

**Comment by herzbube** [comment]
@GeertvanHorrik If you think this would be a good feature, I'd like to offer to code this and submit the changes in another pull request. I haven't thought deeply about a solution yet because I first wanted to see whether you are agreeable to the feature request. The only thing I have seen so far is, roughly, how AvalonWizard does it, and it looks like something that might be usable as inspiration for a solution in Orc.Wizard.

https://avalonwizard.codeplex.com/SourceControl/latest#Source/AvalonWizard/INavigationStrategy.cs

**Comment by GeertvanHorrik** [comment]
This sounds very interesting. The only thing that worries me a bit is that we need to update the breadcrumb consistenly. Or is your idea that we keep the initial page + wizard setup, we just allow the user to skip based on the strategy? If so, then we are really open to a PR :+1:

**Comment by herzbube** [comment]
Yes, my idea is to keep the initial page setup, the feature request is only about navigating between these pages (mainly with the idea to skip some pages).

I did play around with dynamically adding/removing pages, but it became clear soon enough that this is not viable because of the breadcrumb. I mean, it would certainly be possible to code a solution that updates the breadcrumb, but I think a dynamically changing breadcrumb would be rather terrible from the UI design point of view. After all, the breadcrumb is *meant* to be static and give the user a preview of what he can expect from the wizard, so it would probably be quite confusing if that preview suddenly changed e.g. while the user already is in the middle of the wizard. IMHO, client code that wants to implement a dynamically changing page setup would also want to disable the breadcrumb entirely - but that is a different feature request, and one I'm not likely to make because I like the breadcrumb so much :-)

I hope I will be able to start coding on the PR soon, but I also don't want to neglect to mention this: I am currently looking at Orc.Wizard and a couple of other WPF wizard components on behalf of the company that I'm working for. The final decision whether we will start to use Orc.Wizard (and Catel) in our product has still to be made - only then will I be able to start working on the PR. As you might guess, I have already made up my mind in favour of Orc.Wizard, but I will have to defend that personal choice against other solutions that internal company "forces" might prefer.

**Comment by GeertvanHorrik** [comment]
I feel exactly where you are coming from. Just mention to check the latest commit activity of all libraries and they will soon understand which one to pick. And Orc.Wizard gives you access to all the other Orc.* packages (which are awesome as well). Anyway, thanks for the warning upfront. And it's a great idea, so even if you might not have time to do this, I might do it in the future (but can't promise a timeframe, we have lots of stuff to maintain).

**Comment by GeertvanHorrik** [comment]
@herzbube I think we can close this one?
