### ISSUE TITLE
Add quick navigation to step bar wizard header

### ISSUE THREAD

**Issue by GeertvanHorrik** [WildGums/Orc.Wizard#356]
![image](https://user-images.githubusercontent.com/1246444/108596210-cf413800-7383-11eb-82a4-f066b7dbfbb3.png)

We need to add support for "quick navigation" via the step bar wizard header. Note that this is only possible when the pages are optional or free navigation is allowed.

The example app has some options to specify whether navigation to the end is immediately available. If so, we should make the step bar header items clickable so users can directly navigate to a specific page.

Currently users can only navigate forward / backward using the previous / next buttons. In "free navigation mode", we want users to be able to navigate to a specific page directly.

**Comment by kote2ster** [comment]
Hello @GeertvanHorrik I am working on this right now
