### ISSUE TITLE
Consider making the space between the bubbles in the navigation pane autosize

### ISSUE THREAD

**Issue by johncbaur** [WildGums/Orc.Wizard#503]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
My wizard has 8 pages but the height of my wizard is 600 pixels.  It looks like the space between the side by side navigation bubbles are fixed in the XAML.  I am wondering if the distance between the bubbles could be made a property in the view model and then perhaps defaulted by generally dividing the height of the wizard by the number of bubbles.

## API Changes
There are two values in the XAML that need to adjusted.  The Grid margin and the Height of the rectangle used to draw the navigation bubbles. 
## Intended Use Case
This should allow for wizards with more pages without having the navigation pane extend past the window or introduce scrollbars.

**Comment by GeertvanHorrik** [comment]
Sounds like a good plan. Interested in doing a PR?

**Comment by johncbaur** [comment]
Yes, thank you.  I will submit that soon.

**Comment by GeertvanHorrik** [comment]
Thanks again for the PR. Currently releasing a first beta of 4.8.0 that contains this feature. Could you let me know whether it works for you?

**Comment by johncbaur** [comment]
I tested the changes and they all worked for me.  Thanks for accepting the
PR.

We are using the Orc Wizard in an open source project named Vixen Lights
which is used to sequence holiday lights to music.  We are currently
pulling in the Wizard source code as the project is still .NET framework
4.8.  We want to get to the point where we can just use the wizard NuGet
package and this PR was a baby step in that direction.  We are having some
styling conflicts between our application and the Wizard so we may need to
collaborate with you in that regard but our WPF guy needs to look at the
issues first.

**Comment by johncbaur** [comment]
Geert,

I think I have the PR ready but I have questions about the checklist.

I don't really care to be in the contributors file.  Is that OK?
Where is the change log?
I included brief instructions on how to modify the existing example to
exercise the logic.  Do you need something more formal?
Is your coding standard online?

Thanks,
John Baur
