### ISSUE TITLE
Wizard navigation step indicator does not update

### ISSUE THREAD

**Issue by iulian0512** [WildGums/Orc.Wizard#514]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

Orc.Wizard

## Version of Library
 4.8.2

## Version of OS(s) listed above with issue
Windows10 21H1 Build 19043.1889

## Steps to Reproduce
1. Display the wizard
2. User makes a selection in a wizard page then an extra page needs to be added 
3. Add the page using AddPage<TWizardPage>() 
4. The page is added but the top navigation step indicator does not update.

## Expected Behavior
1. The wizard should update the navigation step indicator 

## Actual Behavior
The step indicator is not updated
![image](https://user-images.githubusercontent.com/16035099/187938190-5604fe38-bfef-40dd-af07-61282d95c810.png)

**Comment by GeertvanHorrik** [comment]
Thanks for reporting this behavior. Not sure why we haven't thought of this before :)

I've created a hotfix with the behavior. Please test if the hotfix (beta) works for you. If so, we will release as stable.

**Comment by iulian0512** [comment]
works ok, many thanks.

**Comment by GeertvanHorrik** [comment]
Thanks for the quick reply. Releasing stable version now.
