### ISSUE TITLE
Add TopMost and WindowStartupLocation properties to WizardBase

### ISSUE THREAD

**Issue by iulian0512** [WildGums/Orc.Wizard#520]
## Summary
Add TopMost and WindowStartupLocation properties to WizardBase;

## API Changes
TopMost boolean
WindowStartupLocation see  System.Windows.WindowStartupLocation

## Intended Use Case
The use case is to make the wizard window as easy to use as possbile for novice users that have trouble locating windows and managing them.

**Comment by ceo1647** [comment]
yes, make sense
fixed here: https://github.com/WildGums/Orc.Wizard/pull/621

**Comment by iulian0512** [comment]
#621
