### ISSUE TITLE
Next/Previous buttons

### ISSUE THREAD

**Issue by Allann** [WildGums/Orc.Wizard#8]
Hi.  Not really an issue, more a question on how to disable the next button until an asynchrous task has finished within a wizard page?

I have a task in a WizardPageBase that goes to a server for some data, initiated in the constructor as that it should be ready when the user gets to that page (2nd page). However if it hasn't responded in time, then the next button should be disabled, and then when the task is finished and the page is valid, should the button enable.  

Or is there a better way of doing this?

**Comment by GeertvanHorrik** [comment]
You can use the validation inside view models for this. As long as there are validation errors, the next button won't be enabled.

If that doesn't work for you, I think it's a good idea to implement a "CanMoveNext" on the WizardPage model. Then the WizardBase (which already handles the state) can look at this value to determine if the page can move forward.
