### ISSUE TITLE
wizard with model don`t work

### ISSUE THREAD

**Issue by okunevdm** [WildGums/Orc.Wizard#9]
in MyExampleWizard i add new constructor
public MyExampleWizard(ITypeFactory typeFactory, MyModel model)
          : base(typeFactory)

I try create wizard with model, but i can`t.
_wizardService.ShowWizardAsync<MyExampleWizard>(model);

"Argument 'wizard' cannot be null"

**Comment by mkhomutov** [comment]
just try to change the order of the arguments in your constructor

**Comment by okunevdm** [comment]
ok. thats work. thanks.
but how i can get the result?
ShowWizardAsync from IWizardServiceExtensions rerurn Task, not Task<bool?>

**Comment by GeertvanHorrik** [comment]
The wizard model you injected should have all info?

**Comment by okunevdm** [comment]
i mean:
`MyModel model = new MyModel();`
`IWizardService _wizardService = dependencyResolver.Resolve<IWizardService>();`
`if (_wizardService.ShowWizardAsync<MyExampleWizard>(model) ?? false)`
`       //do work with model`
thats not work, becourse ShowWizardAsync return only Task

**Comment by mkhomutov** [comment]
use 'await':
```
if (await _wizardService.ShowWizardAsync<MyExampleWizard>(model) ?? false)
{

}
```
are you using Catel for dependency resolving?

**Comment by okunevdm** [comment]
i always try it.
yes, i using Catel.
now i work through IUIVisualizerService:
if (await _uiVisualizerService.ShowDialogAsync<WizardViewModel>(wizard) ?? false)
it work.
But through IWizardService dont.

**Comment by mkhomutov** [comment]
looks like a bug? good catch, thanks.
it should work without model injection.

feel free to make a PR for making it work with model as well
